---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - pip install --upgrade pip

install:
  # Install Ansible.
  #- pip install ansible
  - pip install https://github.com/ansible/ansible/archive/devel.zip

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

script:

  - ansible --version

  # check ansible version
  - "[ $(`which ansible` --version| `which cut` -d ' ' -f2) != '2.0.0' ]"
  - "[ $(`which ansible` --version| `which cut` -d ' ' -f2) == '1.9.4' ]"
  - "[ $(`which ansible` --version| cut -d ' ' -f2) == '1.9.4' ]"
  - "[ $(ansible --version| cut -d ' ' -f2) == '1.9.4' ]"
  - >
    [ $(ansible --version| cut -d ' ' -f2) == '1.9.4' ]
    && (echo "Ansible version $(ansible --version| cut -d ' ' -f2): pass" && exit 0)
    || (echo "Ansible version $(ansible --version| cut -d ' ' -f2): fail" && exit 1)


  - ansible --version
  #- if [ $(`which ansible` --version| `which cut` -d ' ' -f2) == '1.9.4' ]; then exit 0; else exit 1; fi