---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

script:

  # check ansible version
  - [ $(`which ansible` --version| `which cut` -d ' ' -f2) == '2.0.0' ]

  - ansible --version

  - [ $(`which ansible` --version| cut -d ' ' -f2) == '1.9.4' ]
  - [ $(ansible --version| cut -d ' ' -f2) == '1.9.4' ]

  - which ansible
  - which cut
  #- if [ $(`which ansible` --version| `which cut` -d ' ' -f2) == '1.9.4' ]; then exit 0; else exit 1; fi