---
language: python
python: "2.7"

env:
  - SITE=test.yml ANSIBLE=1.9.4
  - SITE=test.yml ANSIBLE=2.0.0.1

before_install:
  - sudo apt-get update -qq
  - pip install --upgrade pip

install:
  # Install Ansible.
  - '[[ $ANSIBLE == "http"* ]] && pip install $ANSIBLE || pip install ansible==$ANSIBLE'

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install ansible-lint
  - pip install ansible-lint

script:

  - ansible --version

  # check ansible version
  - >
    [ $(ansible --version| cut -d ' ' -f2) > '1.9.4' ]
    && (echo "Ansible version $(ansible --version| cut -d ' ' -f2): pass" && exit 0)
    || (echo "Ansible version $(ansible --version| cut -d ' ' -f2): fail" && exit 1)


  - ansible --version

  - echo pwd
  #- if [ $(`which ansible` --version| `which cut` -d ' ' -f2) == '1.9.4' ]; then exit 0; else exit 1; fi

after_failure:
  - echo pwd
  - ls -l
  - cat ansible.cfg
  - cat /home/travis/build/tschifftner/travis-tests/ansible.cfg

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
