sudo: required
services: docker

env:
  global:
    - DEBUG=true
    - secure: "GOw2BZ9vWu1WfANUVm1Okr4dSBwghaf5FBiJXb6mgp3UeODNSAMX4N/Y3yUNMsZdHJgEYckMclP/gfxnQVxKnhGy+zibeITFd/Jmmh9tNEPLG16orIOo3238EX0dOPnIzxoh0XLydx+4rnzFm51o3MZNIcPrCCSgIDwK9H3ghC76ssZ34pTjVXJPL/dJKcJqc9LWdkQKaediAAB3S6ZaKApXW1HQa6jmFTdyE9bzcXE0Lr6x92snL4xo1KqR1DH9BW62nA3ypakuo4P4leoSRHe9GhCrAUg1rAJZ7Iay0VO4jPVhE1A7RDeBWGqEIvvPLdWtVsV/LHa4mooEUvuS55vhAPLFD2m2WnsZIoydQbESyeShVCxqH8FvuInVPJH4k0AXYd9jlUl8zvebZ8sqHSNfereF/FRo77GlBCJFB7AGI2f0cTYtnGTwufGNBc8yobmWTfDRZfbChrn3H7TTcvZA/+gfRafTHcA0JNwozcn6L+3SQN3wE1TmkwNP7hkqwh0wC6VizTX66LUu4xs2oGCITRzdtTSjP7M1GHzlsqBcNSJvdkiZ3kxcEQ7NCBFfj3W0FFr9PfC1hRnV3JuAoo4uELzaWPAUYMEaKhhgkn8HfxyLgmXnP4OU64SySCft2dLKXMDFWbHuAhiGxtPPwXI2BjTUQIefi3mY+YZWXSE="
    - secure: "YFoyj4uSY26ymcKXcdDSbbHEMj6ZNyF5I4tP5FPG2054/hNF4haI7rtgLoxgik2GtJN0vu9lQqQ46SmvIsK3RTU22WaHFSOqNozaEshXSgjzkVzulTSqKWoCPyN6TNr0ffsXxwr/m2VtUHUHfhxFfXFCL++Am9nlggHpaY1Bf2N8KJ/OroHAAyo2uHfH4PrFsgODNb6hCNkX++kOZK5rZ+oYkNeAxOzJnlrHldkRLSGLFElJSHUs7a9xHYqrSeowlVXqOlEehG9zldx1szECFhoBrgKLOhitq+iDLVG9sUd0jVRit9Gzrr2BNpzBGqJyvF07SOwd/rvu9sWyioCaY7QOMzU6DjkixLLnFAVOXtZazWQ8EdjSUSSpZLwjMwYO7G2J0uFKoJ+dMQAM91OLxYAC+5njhI72wrt7YNeRe3SriognSwOEL6jRDOX/IfedEhWMkjJCc4axD5Ap6MNufhU1KHi/20ZtJwoeGjZVKSlUfkT3wEI3jBpf79IdGe67RsMnijHNz6N3FPud2lPnOh68jDaQG1pKHMWrzKL0QlpIf+k4iqL0zpEuebcLlV6lGTuZVun4oNhY7iVI53+29R02Ol7seSSfML6sXc26/2OTj5XoWIR7YNmxmVJ/gruuypvDRXq6Z2zkHsz0aE5JIvY+MhsWSU35JRghATha178="

script:
  - export image="ambimax/travis-tests"
  - docker build -t "$image" .
  - docker run $image /usr/local/bin/composer --version

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - pip install docker-ci-deploy==0.3.0

deploy:
  provider: script
  script: docker-ci-deploy --tag $(git rev-parse --short HEAD) --tag latest "$image"
  on:
    branch: master
#    condition: $TRAVIS_PULL_REQUEST = "false"